### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by Shatur** [milisims/nvim-luaref#9]
Hi! Thank you a lot for the awesome plugin. Could you add Russian language version?

**Comment by milisims** [comment]
Hi there! I have only added languages from (available translations for the 5.1 reference manual)[https://www.lua.org/manual/]. I have not done polish, and russian is only available for 5.3.

I'll look into this and keep you updated, but I might decide not to do it, because I need to write a `toc` for russian and apply special edits for the 5.3 version.

**Comment by Shatur** [comment]
I didn't know that only presented languages are officialy available. Perhaps it is better to leave only those.
